language: ruby
rvm:
  - 2.6.4
  - 2.6.3
  - 2.6.2
  - 2.6.1
  - 2.6.0
  - 2.5.6
  - 2.5.5
  - 2.5.4
  - 2.5.3
  - 2.5.2
  - 2.5.1
  - 2.5.0
  - 2.4.6
  - 2.4.5
  - 2.4.4
  - 2.4.3
  - 2.4.2
  - 2.4.1
  - 2.4.0
  - 2.3.8
  - 2.3.7
  - 2.3.6
  - 2.3.5
  - 2.3.4
  - 2.3.3
  - 2.3.2
  - 2.2.10
  - 2.2.9
  - 2.2.8
  - 2.2.7
  - 2.2.6
  - 2.2.5
  - 2.2.4
  - 2.2.3
  - 2.2.2
  - 2.2.1
  - 2.2.0
  - 2.1.10
  - 2.1.9
  - 2.1.8
  - 2.1.7
  - 2.1.6
  - 2.1.5
  - 2.1.0
  - 2.0.0-p648
notifications:
  email: false
  slack:
    secure: dSwRumGlIAdGDAaH/fzh/KsQhRqPBcNpbGYrMbAzacFMm8nGyLCShxR3EP/ZxkBp14ZsJ8ys4F5DMVlri7EbGNgBf1nOKAtzme6lV8oqrUxW2QULgvrP4W/+xTg1ULX758qF5NgwqErfS4Y1etofMbOuGriJ6kIxFWRjidmFPYo=
